FROM rustcompile  # A base image (debian) containing rustc (same version) and cargo

WORKDIR /tmp

COPY . /tmp/
#RUN cargo build --target=x86_64-unknown-linux-musl --release
RUN cargo build --target=x86_64-unknown-linux-musl --release
